version: '2'
services:
  nginx:
    container_name: blog-nginx
    image: nginx:1.15
    restart: always
    ports:
      - 80:80
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d

networks:
  default:
    external:
      name: vueblog_bridge
